### ISSUE TITLE
Is there any requirement on deleted blocks (all 0xFFFF..., all 0x0000...)?

### ISSUE THREAD

**Issue by ProfDrYoMan** [ARMmbed/littlefs#115]
Hi,

I can not find any clear information if it is a requirement that deleted blocks show data 0xFFFF...

I might use this FS for the case that deleted blocks show data 0x0000...

Is this ok with the current implementation? If not, what needs to be changed to get this done?

Thanks in advance.

**Comment by geky** [comment]
Hi @ProfDrYoMan, I like your username. 

Deleted blocks showing 0x0000 is not an issue. littlefs doesn't trust blocks it hasn't erased itself and always erases before writing to a block it does not know about.

**Comment by ProfDrYoMan** [comment]
Ok, nice to here that it still works if deleted flash blocks show 0X0000... (which is not very common). 

Thanks for the fast answer. Will put it into a test project tomorrow.

**Comment by geky** [comment]
Out of curiousity, what type of storage are you using that erases to 0x0000?

**Comment by ProfDrYoMan** [comment]
It's an Infineon AURIX.
