### ISSUE TITLE
Overwriting of a flash location?

### ISSUE THREAD

**Issue by davidefer** [ARMmbed/littlefs#121]
Hi @geky,
I've tried to find this info in the documentation but I was not successful.
Does LittleFS perform overwriting of a location in flash relying on the fact that bits can be set from 1 to 0? This would be a problem for me, because the internal flash of my processor doesn't allow this kind of operation.
Thanks in advance.
Cheers.

**Comment by e107steved** [comment]
No it doesn't - see discussion in https://github.com/ARMmbed/littlefs/issues/77

**Comment by ProfDrYoMan** [comment]
And also #115.

**Comment by davidefer** [comment]
ok thanks. I'll then try it out.
