### ISSUE TITLE
Improve write throughput

### ISSUE THREAD

**Issue by EPZpze** [ARMmbed/littlefs#125]
Hello,
I'm using LittleFS v1.7 with NXP kinetis family, dual QuadSPI with two S25FS512S in parallel mode.
I need to save data in real time, 250 kbytes/sec for 2 seconds. On a fresh install, the throughput is pretty good, but when the file system lived a little, blocks needs to be erased and performances are dramatically decreased, because of the very long time sector erase (typ. 930ms/256kb sector).
Is it possible to erase 1M bytes blocks ahead before calling lfs_file_write() to ensure a good throughput?

Thanks,
Emmanuel

**Comment by rojer** [comment]
@EPZpze looks like you need to implement something similar to what @geky described here: https://github.com/ARMmbed/littlefs/issues/108#issuecomment-424790391

**Comment by EPZpze** [comment]
Hi,
I did something quick & dirty (but it works), I use lfs_alloc with a duplicated lfs_t structure and a copy of the lfs->free.buffer, it just waste about 70 bytes of ram.
I did something like that:

`// Erase a number of block ahead
int lfs_erase_block_ahead(lfs_t *lfs, int block2Clear)
{
lfs_t cpylfs;	/* Consume 68 byte on stack with cortex-M4, could be a global var */
lfs_block_t myBlock;
int err = LFS_ERR_OK;
uint32_t buff_ahead[lfs->cfg->lookahead/32];
	memcpy(&cpylfs, lfs, sizeof(cpylfs));	/* make a copy of lfs structure */
											/* make a copy of buffer */
	memcpy(buff_ahead, lfs->free.buffer, sizeof(uint32_t)*lfs->cfg->lookahead/32);

	cpylfs.free.buffer = buff_ahead;		/* replace the pointer */

	for(int i=0 ; i < block2Clear; i++)
	{
		err = lfs_alloc(&cpylfs, &myBlock);
		if(err)
			break;
		err = lfs_bd_erase(&cpylfs, myBlock);
		if(err)
			break;
	}
	return err;
}
`

**Comment by ajaybhargav** [comment]
@EPZpze I am in a similar situation. Saving file takes about 2sec and task is kind of halted for that time. how is the write speed after the above implementation? and how often do you call this function?

**Comment by EPZpze** [comment]
@ajaybhargav 
You have to call this function, each time you want a guaranteed throughput. 
Most of the time, flash memories are slow to erase and rather fast to write.
