### ISSUE TITLE
lookahead_size description is inconsistent in v2-alpha

### ISSUE THREAD

**Issue by amitv87** [ARMmbed/littlefs#147]
The comment in the c file says **lookahead_size must be a multiple of 4**
https://github.com/ARMmbed/littlefs/blob/v2-alpha/lfs.c#L3222

And comment in headers says **lookahead_size must be multiple of 64-bits (8 bytes)**
https://github.com/ARMmbed/littlefs/blob/v2-alpha/lfs.h#L208

**Comment by geky** [comment]
Thanks for creating an issue! I've updated this on the v2-alpha branch (https://github.com/ARMmbed/littlefs/pull/85), let me know if you see any other mistakes.

Related https://github.com/ARMmbed/littlefs/issues/134
