### ISSUE TITLE
Making littlefs thread-safe?

### ISSUE THREAD

**Issue by rbphilip** [ARMmbed/littlefs#156]
Hey! I just found littlefs and am porting it this morning to a FreeRTOS system with 128MB NOR flash. 

I see that littlefs doesn't have any sort of thread-safe mechanism built in. That's fine and I've seen references to wrapping littlefs calls with semaphores. Also fine. 

The question is *which* calls need to be wrapped. open/close/read/write/??

Anything that has a prototype in lfs.h? That'll likely be my first stab at it, but perhaps this is an issue that someone else has resolved in an elegant manner..

Thanks for any insights.

**Comment by FreddieChopin** [comment]
> The question is which calls need to be wrapped. open/close/read/write/??

Everything which is an user-facing public API.

For an example see this port:
https://github.com/DISTORTEC/distortos/tree/master/source/FileSystem/littlefs
https://github.com/DISTORTEC/distortos/tree/master/include/distortos/FileSystem/littlefs

**Comment by rbphilip** [comment]
Unfortunately I have zero experience with C++. Is "const std::lock_guard<LittlefsFile> lockGuard {*this};" a semaphore "take"? 

Is this "return" the semaphore "give" "return {{}, ret};"

**Comment by FreddieChopin** [comment]
> Is "const std::lock_guard lockGuard {*this};" a semaphore "take"?

Yes.

> Is this "return" the semaphore "give" "return {{}, ret};"

Not exactly. Any possible exit from this function will destroy this `lockGuard` object, which will cause its destructor to be executed, which in turn releases the mutex. Generally any exit from this function causes automatic release of the mutex.

Please also don't confuse mutex and semaphore - the fact that in FreeRTOS they are "almost the same thing" (one of many stupid things in FreeRTOS...) doesn't mean that they are meant for the same purpose.

**Comment by rbphilip** [comment]
Thanks. 

It appears that there is a different mutex used for directories than for files. Do you perhaps know if this is true (again, I don't really grok C++) and if so, why?

**Comment by FreddieChopin** [comment]
There are no separate mutexes for file and directory objects - there is only one recursive mutex per file system and locking the file or directory is achieved by locking the mutex in the associated file system.

`lockGuard` is only a RAII (look it up) object which locks/unlocks the mutex/object that you provide. The "thing" you provide just has to have `lock()` and `unlock()` functions which will be called in constructor and destructor respectively.

Here's the only mutex in these clases:
https://github.com/DISTORTEC/distortos/blob/master/include/distortos/FileSystem/littlefs/LittlefsFileSystem.hpp#L290

Note that there is no such mutex in file or directory classes. If you lock the file manually this calls `lock()` of associated file system:
https://github.com/DISTORTEC/distortos/blob/master/source/FileSystem/littlefs/LittlefsFile.cpp#L100
which in turn just locks the common mutex:
https://github.com/DISTORTEC/distortos/blob/master/source/FileSystem/littlefs/LittlefsFileSystem.cpp#L307

But you don't have to manually lock anything. Each function does its own locking (with the `std::lock_guard`). The `lock()` and `unlock()` functions are required only if you want to perform several operations "atomically", for example you need to do 10 writes back-to-back and don't want any write from other thread to mix things up (for example you are writing to a shared log file but you cannot write the complete entry with one call and need several of them).

**Comment by rbphilip** [comment]
Thanks. C++ continues to seem unnecessarily obscure and unnecessarily complex to me. I suppose that comes from learning to program back when "C" was a new language. :)  

Can I distill down that what I need to do for each of the lfs externally visible functions to something like this:

int my_getsize(
{
    xSemaphoreTake( fs_mutex,0xffffffff);
  int size = lfs_file_size(&fileSystem_.fileSystem_, &file_);
   xSemaphoreGive( fs_mutex );
   return size;
}

**Comment by FreddieChopin** [comment]
Yes.

**Comment by rbphilip** [comment]
Thanks for the help.

**Comment by geky** [comment]
Sounds like everything got sorted out here? Thanks @FreddieChopin! Let me know if this issue needs to be reopened.

**Comment by rbphilip** [comment]
Yes - everything is working fine. As a future feature request it would be a lot easier to do thread-safe if there was the possibility of a "get a mutex" and "release a mutex" function configuration, and LittleFS called them itself at the appropriate places.

**Comment by geky** [comment]
Not a bad idea, assuming 1. out of the box had default stubs (similar to lfs_malloc) and 2. stubs did not increase existing code size.

Unfortunately, this is low priority at the moment. I'd be happy to take in a PR, but I think there's some bigger issues to take care of first.

**Comment by henrygab** [comment]
This is just an update of @FreddieChopin 's links:

#### Mutex:
https://github.com/DISTORTEC/distortos/blob/79062407feef8b80b28929610f4eb4e13e467b29/include/distortos/FileSystem/Littlefs1FileSystem.hpp#L309

#### File/Directory's `lock()`:
https://github.com/DISTORTEC/distortos/blob/746afae4c4d8485c9aafc572364861c6ac6de223/source/FileSystem/littlefs1/Littlefs1File.cpp#L94-L97

#### Filesystem-wide `lock()`:
https://github.com/DISTORTEC/distortos/blob/746afae4c4d8485c9aafc572364861c6ac6de223/source/FileSystem/littlefs1/Littlefs1FileSystem.cpp#L265-L269

**Comment by johnnytolengo** [comment]
Hello  @rbphilip, could you provide us an example of the wrapper you did?  I have the same situation here and I have not clue how to do that thread-safe wrapper.

Thank you

**Comment by rbphilip** [comment]
Sorry. That was several clients ago.

But basically create wrapper functions for all the littlefs calls, and 
use a semaphore to "lock" access to the littlefs library.. something 
like below.

somewritefunction (data, size)
{
      take semaphore
      call littlefs function to write
      release semaphore
}

**Comment by johnnytolengo** [comment]
yes, but that is already build in look here: https://github.com/lorol/LITTLEFS/blob/master/src/esp_littlefs.c#L662

I think the only problem is around the file descriptor when the file is opened multiple times: https://github.com/joltwallet/esp_littlefs/pull/19

I am not sure if that is already solved in the https://github.com/lorol/LITTLEFS

I it's all about thread-safty  :(

**Comment by rbphilip** [comment]
It's been years since I even thought of littlefs.

**Comment by FreddieChopin** [comment]
@rbphilip :

> It's been years since I even thought of littlefs.

Have you maybe found some nice alternatives to it? (;

**Comment by rbphilip** [comment]
Sorry, no.

It worked well for the client at the time but I haven't had need for a 
file system on any projects since then.

**Comment by amgross** [comment]
Just to mention to whoever get to here, there is now thread safe embedded in littlefs when defining LFS_THREADSAFE
