### ISSUE TITLE
lfs_mkdir after lfs_dir_open (forgetting lfs_dir_close) hardfaults

### ISSUE THREAD

**Issue by meh** [ARMmbed/littlefs#164]
Seems like `lfs_mkdir` decides to explode in your face instead of returning an error if you're still iterating over directories.

Branch in use is latest `v2-alpha`.

**Comment by apmorton** [comment]
Without seeing the code you used to produce the error I can't say for sure, but this is probably the same issue as #145 

TL;DR; `lfs_file_open` and `lfs_dir_open` put the file/dir object you give them into a linked list of all open files/directories.  `lfs_file_close` and `lfs_dir_close` remove the entry from that list.  If you forget to close a file/directory and then the `lfs_file_t`/`lfs_dir_t` goes out of scope (for example if you allocate it on the stack and then return from the function), when calling many lfs functions you will end up dereferencing a pointer that may have been clobbered, resulting in undefined behavior.

**Comment by FreddieChopin** [comment]
> Without seeing the code you used to produce the error I can't say for sure, but this is probably the same issue as #145

I suppose the issue here is something more like:

lfs_dir_open()
...
lfs_mkdir()
...
lfs_dir_close()

**Comment by apmorton** [comment]
I am not able to reproduce that, but I can reproduce a crash when "forgetting" to close a directory (open the directory, then memset the whole thing to `0xAA` to simulate stack corruption, and then try to call mkdir.

Complete test script below.
Relevant bits in `Directory iteration mkdir` and `Directory iteration double open`


```bash
#!/bin/bash
set -eu

LARGESIZE=128

echo "=== Directory tests ==="
rm -rf blocks
tests/test.py << TEST
    lfs_format(&lfs, &cfg) => 0;
TEST

echo "--- Root directory ---"
tests/test.py << TEST
    lfs_mount(&lfs, &cfg) => 0;
    lfs_dir_open(&lfs, &dir[0], "/") => 0;
    lfs_dir_close(&lfs, &dir[0]) => 0;
    lfs_unmount(&lfs) => 0;
TEST

echo "--- Directory creation ---"
tests/test.py << TEST
    lfs_mount(&lfs, &cfg) => 0;
    lfs_mkdir(&lfs, "potato") => 0;
    lfs_unmount(&lfs) => 0;
TEST

echo "--- File creation ---"
tests/test.py << TEST
    lfs_mount(&lfs, &cfg) => 0;
    lfs_file_open(&lfs, &file[0], "burito", LFS_O_CREAT | LFS_O_WRONLY) => 0;
    lfs_file_close(&lfs, &file[0]) => 0;
    lfs_unmount(&lfs) => 0;
TEST

echo "--- Directory iteration ---"
tests/test.py << TEST
    lfs_mount(&lfs, &cfg) => 0;
    lfs_dir_open(&lfs, &dir[0], "/") => 0;
    lfs_dir_read(&lfs, &dir[0], &info) => 1;
    strcmp(info.name, ".") => 0;
    info.type => LFS_TYPE_DIR;
    lfs_dir_read(&lfs, &dir[0], &info) => 1;
    strcmp(info.name, "..") => 0;
    info.type => LFS_TYPE_DIR;
    lfs_dir_read(&lfs, &dir[0], &info) => 1;
    strcmp(info.name, "burito") => 0;
    info.type => LFS_TYPE_REG;
    lfs_dir_read(&lfs, &dir[0], &info) => 1;
    strcmp(info.name, "potato") => 0;
    info.type => LFS_TYPE_DIR;
    lfs_dir_read(&lfs, &dir[0], &info) => 0;
    lfs_dir_close(&lfs, &dir[0]) => 0;
    lfs_unmount(&lfs) => 0;
TEST

echo "--- Directory iteration mkdir ---"
tests/test.py << TEST
    lfs_mount(&lfs, &cfg) => 0;
    lfs_dir_open(&lfs, &dir[0], "/") => 0;

    lfs_mkdir(&lfs, "test") => 0;
    lfs_dir_read(&lfs, &dir[0], &info) => 1;
    strcmp(info.name, ".") => 0;
    info.type => LFS_TYPE_DIR;
    lfs_dir_read(&lfs, &dir[0], &info) => 1;
    strcmp(info.name, "..") => 0;
    info.type => LFS_TYPE_DIR;
    lfs_dir_read(&lfs, &dir[0], &info) => 1;
    strcmp(info.name, "burito") => 0;
    info.type => LFS_TYPE_REG;
    lfs_dir_read(&lfs, &dir[0], &info) => 1;
    strcmp(info.name, "potato") => 0;
    info.type => LFS_TYPE_DIR;
    lfs_dir_read(&lfs, &dir[0], &info) => 1;
    strcmp(info.name, "test") => 0;
    info.type => LFS_TYPE_DIR;

    lfs_mkdir(&lfs, "aaa") => 0;
    lfs_dir_read(&lfs, &dir[0], &info) => 0;

    lfs_mkdir(&lfs, "zzz") => 0;
    lfs_dir_read(&lfs, &dir[0], &info) => 0;

    lfs_dir_close(&lfs, &dir[0]) => 0;
    lfs_unmount(&lfs) => 0;
TEST

echo "--- Directory iteration double open ---"
tests/test.py << TEST
    lfs_mount(&lfs, &cfg) => 0;
    lfs_dir_open(&lfs, &dir[0], "/") => 0;

    // simulate memory corruption
    memset(&dir[0], 0xAA, sizeof(dir[0])) => &dir[0];

    // this will crash the test with a segfault
    lfs_mkdir(&lfs, "test2") => 0;
    lfs_unmount(&lfs) => 0;
TEST


echo "--- Results ---"
tests/stats.py
```

**Comment by meh** [comment]
@apmorton yeah I think those tests are what I'm experiencing.

**Comment by apmorton** [comment]
If that's the case, this is pretty much a dup of #145, and the solution is pretty much "don't do that"

Always close your file/directory when the `lfs_file_t` or `lfs_dir_t` goes out of scope.

See my comments on #145 for potentially more helpful mitigations (tl;dr; use c++ wrappers that enforce correct behavior with destructors).

**Comment by meh** [comment]
@apmorton yeah I'm in the process of writing a C++ wrapper :panda_face: 

I was just hoping there was a way to return errors instead of exploding when iterators get invalidated.

**Comment by meh** [comment]
I'm going to go through #145 and comment there if I have anything additional, sorry for the issue tracker noise!
