### ISSUE TITLE
How to get free, useable remaining space?

### ISSUE THREAD

**Issue by Mohawi** [ARMmbed/littlefs#186]
Hi, I'm wondering how to get the remaining (estimated) free, useable space of the configured block count of littleFS.
I can get the currently used space by calling `lfs_fs_traverse`. But how can I get the amount of already worn out blocks? Is there a neat way to do it?

**Comment by sshaw-lutron** [comment]
I don't believe that littleFS actually keeps track of warn out blocks, it just moves to a new block when it detects a write failure. I suspect there _isn't_ a neat way of figuring out the number of bad blocks.
 
Also, `lfs_fs_size` returns the number of allocated blocks (basically does the `lfs_fs_traverse` calls for you). Might be a little easier to use ;-)

**Comment by Mohawi** [comment]
Mh, ok. I see.

Thanks for pointing out the `lfs_fs_size`.
