### ISSUE TITLE
双flash挂在文件系统乱码

### ISSUE THREAD

**Issue by wanghongze** [ARMmbed/littlefs#211]
你好，我在使用过程中挂载了2个文件系统，每个文件系统都有对应的lfs_cfg和lfs，但在使用过程中，挂载一个文件系统时，不论写多大，读出来都正常，但是如果挂载2个，写之后再读取，读到的内容都错乱了，应该如何解决呢

**Comment by geky** [comment]
I will assume you found a solution. Feel free to reopen if you still have a problem. 👍
