### ISSUE TITLE
find the existing files  

### ISSUE THREAD

**Issue by friguimahdi** [ARMmbed/littlefs#219]
Hello, 

Is there any possible way to know what are the files that exists ? (name at least)

**Comment by friguimahdi** [comment]
Its done using lfs_dir_read

**Comment by Johnxjj** [comment]
if we don't know the file name,  how to know what are the files that exists?

**Comment by friguimahdi** [comment]
you need to open the target directory that contains the files then you just read it using a while loop.

ret = lfs_dir_open(&lfs,&dir,"/");
   do
   {
    lfs_dir_read(&lfs,&dir,&info);
    if(info.name[0]!='.')
    {
    BSP_LCD_DisplayStringAtLine(i,(uint8_t*)info.name); /* Displaying the file names at line i */
    i++;
    }
   }while(info.name[0]!='\0');
   ret = lfs_dir_close(&lfs,&dir);

**Comment by Johnxjj** [comment]
Thank you for the code provided very much, which helped me a lot!
