### ISSUE TITLE
GCC warning about memcpy overlap in lfs_emubd.c

### ISSUE THREAD

**Issue by DanielLyubin** [ARMmbed/littlefs#229]
At the end of lfs_emubd_prog there is a history update using memcpy. The compiler says there is a memory overlap because it tries to write 12 bytes to history.blocks[1]  from history.blocks[0].
I understand that you try to shift right the array by one cell (unless it's something else and in that case I'd like an explanation). This method must assume memcpy writes data using temporary buffer or writes data from higher address to lower address, but in case it writes to the target address in-place from lower address to higher address, the history blocks array will include only the value of blocks[0] in each cell.

**Comment by geky** [comment]
Ah! So you're right, good catch.

This should take care of that https://github.com/ARMmbed/littlefs/pull/230
