### ISSUE TITLE
write-rewind overlay occurs,the write speed inefficiency

### ISSUE THREAD

**Issue by geniusgogo** [ARMmbed/littlefs#246]
HI,ALL.
I have a cache file that is fixed length, each cached data is 200 bytes, and a total of 5,000 caches. 
File writes are very slow (about 20 seconds) when a write-rewind overlay occurs.

**Comment by geniusgogo** [comment]
I used multiple file separation storege

**Comment by geky** [comment]
Glad you were able to find a workaround, this issue covers the same underlying limitation: https://github.com/ARMmbed/littlefs/issues/244
