### ISSUE TITLE
[Question] Can you determine the starting block for the FS?

### ISSUE THREAD

**Issue by joel-felcana** [ARMmbed/littlefs#255]
Hi,

I understand that you can limit how much your FS extends into your flash by setting the block_count parameter, but how can you determine the starting block? My device writes the OTA update binaries to raw flash (as they must be parsed by the bootloader), and uses flash addresses 0 to 512KB. If I just erase them before an OTA, I (potentially) lose the FS. It's not a dealbreaker, I can start with a fresh FS after an update because I assume that an OTA will cause data loss, but I was just wondering, because I swear I read something about multiple, concurrent FS, but I can't find it now.

**Comment by e107steved** [comment]
https://github.com/ARMmbed/littlefs/issues/176
https://github.com/ARMmbed/littlefs/issues/204

**Comment by joel-felcana** [comment]
Thanks! I knew I read about it somewhere...
