### ISSUE TITLE
Bug in test "Really big path test"

### ISSUE THREAD

**Issue by mr-at-eo** [ARMmbed/littlefs#293]
https://github.com/ARMmbed/littlefs/blob/fd204ac2fb4e05ffce6db6d1be67e0342c267cd7/tests/test_paths.sh#L182

Should be 

    path[LFS_NAME_MAX] = '\0';

memset goes from 0 to MAX-1, then MAX is the next one. Since path is initialize with zeors, before main, the problem does not show up currently.

same thing in line 196

**Comment by geky** [comment]
Good find! I put up a pr here #294. Were you running the tests in an environment without zero-initialization?

**Comment by mr-at-eo** [comment]
I'm trying to stuff all the tests in one C function and execute them on the embedded device against the actual block device. So i had older stuff in the path variable.

**Comment by geky** [comment]
closing as fixed, feel free to reopen if mistaken.
