### ISSUE TITLE
How can I use little fs in zephyr?

### ISSUE THREAD

**Issue by lucaspeixotot** [ARMmbed/littlefs#314]
I'm working in zephyr and I'm using a driver that already exists, but I'm thinking o start to use little fs. How can I make this works? I'm working with a SD card. Do you guys have some start point?

**Comment by geoffrey-vl** [comment]
What about [this](https://docs.zephyrproject.org/latest/samples/subsys/fs/littlefs/README.html)?

**Comment by geky** [comment]
Let us know if @geoffrey-vl's link helps. Otherwise you may need to open an issue on Zephyr itself. The API will differ from OS to OS but feel free to come back here if you have questions on the underlying workings of the filesystem.
