### ISSUE TITLE
MDK compiler v5.27.1 warning

### ISSUE THREAD

**Issue by geniusgogo** [ARMmbed/littlefs#325]
lfs.c(980): warning:  #68-D: integer conversion resulted in a change of sign
      return (int)lfs_dir_fetchmatch(lfs, dir, pair, -1, 0, NULL, NULL, NULL);

**Comment by geky** [comment]
Hi @geniusgogo, thanks for creating an issue. Does this change fix the warning to you: https://github.com/ARMmbed/littlefs/pull/337/commits/60e67ae080d016ed5c6e9140acf561ba97a838fb?

I've added it to this PR: https://github.com/ARMmbed/littlefs/pull/337

**Comment by geky** [comment]
I believe this is resolved, feel free to reopen if otherwise.
