### ISSUE TITLE
lfs_dir_read and lfs_dir_tell mismatch in root directory

### ISSUE THREAD

**Issue by jhartika** [ARMmbed/littlefs#328]
LittleFS has some inconsistencies in how root directory is handled.
Value of _lfs_dir.m.count_ is one larger than actual number of entries.
Iterating with _lfs_dir_read_ skips over one _lfs_dir.id_ value (skips the extra entry I assume).
As side effect this skip leaves _lfs_dir.id_ and _lfs_dir.pos_ desynced and causes _lfs_dir_tell_ to return incorrect values.

**Comment by geky** [comment]
So it does! Thanks for reporting this.

The issue was related to the superblock entry, which looks like a file, but isn't an actual file. Put up a PR here: https://github.com/ARMmbed/littlefs/pull/340
