### ISSUE TITLE
Confused about path lengths

### ISSUE THREAD

**Issue by nickray** [ARMmbed/littlefs#353]
Apologies if this is obvious, but does `LFS_NAME_MAX` apply to all paths, or only file names (in the sense of the final component of a path)?

**Comment by geky** [comment]
Hi @nickray, `LFS_NAME_MAX` only applies to filenames. It mirrors the POSIX [NAME_MAX](https://pubs.opengroup.org/onlinepubs/009695399/basedefs/limits.h.html) constant.

There is no limit on the path length other then the RAM and storage you have on your device. lfs_file_open makes sure to write the file name to disk and doesn't keep it around.

As a sidenote, this is why creating a new file creates a file with zero size on disk, even if you haven't written to it yet.

**Comment by nickray** [comment]
Thanks!
