### ISSUE TITLE
How do I allocate lookahead cache

### ISSUE THREAD

**Issue by Johnxjj** [ARMmbed/littlefs#388]
A larger lookahead buffer increases the number of blocks found during an allocation pass. 

How do I understand this sentence. My configuration is：

#define LFS_LOOKAHEAD_SIZE       32
uint32_t ullfs_lookahead_buf[LFS_LOOKAHEAD_SIZE];   //   LFS_LOOKAHEAD_SIZE = 256/8 = 32

g_cfg.block_size = 4096
g_cfg.block_count = 256
g_cfg.lookahead_buffer = ullfs_lookahead_buf; 
g_cfg.lookahead_size = LFS_LOOKAHEAD_SIZE;

If I increase the lookahead cache to 40, will the file system speed increase? Will the speed of finding blocks increase?

**Comment by geky** [comment]
Hi @Johnxjj, sorry about the late response.

The allocator needs to do a scan which is expensive. Increasing the lookahead cache size reduces the number of scans needed. But littlefs will still need to do the first scan.

So increasing the cache size can speed up a filesystem, unless the you are limited by the time it takes to do the first scan.

The performance of the allocator scan is one of the big issues needing fixing in littlefs and is being tracked here:
https://github.com/ARMmbed/littlefs/issues/75
