### ISSUE TITLE
lfs_remove return error:-28

### ISSUE THREAD

**Issue by cw339004111** [ARMmbed/littlefs#423]
when set block_size to 64,use lfs_remove delete first directory of directory list,return -28,delete other directory is ok,change block_size to 128 or lager,it will be ok

**Comment by e107steved** [comment]
There is a minimum block size needed to accommodate littleFS overhead, which I'm pretty certain is 128. (The answer is buried in geky's replies to an issue somewhere).

**Comment by cw339004111** [comment]
thank you for reply
