### ISSUE TITLE
[Question] Is it supported that block_size set to be the same as prog_size?

### ISSUE THREAD

**Issue by gofortime** [ARMmbed/littlefs#445]
Hi expert,

I am wondering is it OK to set the block_size set to be the same as prog_size? It there any predictable side effect to do so?

Thanks,
Wenjun

**Comment by e107steved** [comment]
No problem with block_size and prog_size having the same value - I am using it.

Note that the minimum value for block_size is 128 bytes.

**Comment by gofortime** [comment]
> No problem with block_size and prog_size having the same value - I am using it.
> 
> Note that the minimum value for block_size is 128 bytes.

Good. Thanks a lot for the reply~

**Comment by gofortime** [comment]
issue closed.
