### ISSUE TITLE
Using littlefs with multiple blocks of flash

### ISSUE THREAD

**Issue by FreddyBZ** [ARMmbed/littlefs#455]
Sorry to file it as an "issue" - but I cannot find any forum for questions.

Can I configure LittleFS to use multiple flash memory blocks as one file system?

Thanks,

Freddy

**Comment by geky** [comment]
Currently issues are the best place for discussion, but open to other ideas (maybe [github discussions](https://github.blog/2020-05-06-new-from-satellite-2020-github-codespaces-github-discussions-securing-code-in-private-repositories-and-more/#discussions) when they're released?)

> Can I configure LittleFS to use multiple flash memory blocks as one file system?

Yes, though the filesystem itself isn't really aware.

To bring up LittleFS you need to provide a block device driver. This is a mapping from LittleFS's logical block number and offset to the address on your storage device. Normally this can be just a wrapper around a block device driver, but you're free to do any additional math to the block+offset as a part of the mapping.

Assuming two blocks of flash, you access could look something like this (pseudocode):
``` c
bd_read(lfs_block_t block, lfs_off_t off, void *buffer, lfs_size_t size) {
    if (block < FLASH1_SIZE/ERASE_SIZE) {
        flash1_read(block, off, buffer, size);
    } else {
        flash2_read(block - FLASH1_SIZE/ERASE_SIZE, off, buffer, size);
    }
}
```
