### ISSUE TITLE
LFS creation fails if some blocks are bad

### ISSUE THREAD

**Issue by rojer** [ARMmbed/littlefs#71]
`lfs_format` fails if some of the blocks used cannot be read.
LFS should not care about previous contents of blocks and should deal with bad blocks in the same manner as during normal operation.
in fact, sometimes blocks can be made readable by erasing them first (e.g. previous ECC error).

**Comment by geky** [comment]
Oh interesting. So you're getting ECC errors on the first writes to the blocks 0 and 1? Is this a heavily used storage chip?

During format, littlefs doesn't trust any data on the blocks and should be erasing any blocks it uses before it writes data to them. Does this not match what you are seeing?

A part of the design of littlefs is that it relies on a superblock pair stored in blocks 0 and 1. These blocks are written to very rarely, so they shouldn't become worn during normal use. Unfortunately, if these blocks are already unwritable, littlefs doesn't have a backup mechanism to find the superblock (I'm open to ideas on what to do in this situation, but there is also a code size concern).

If blocks 0 and 1 are bad, you can configure the block device to skip 0 and 1 and present 2 and 3 as the first two blocks. However this is a bit clumsy, and may be difficult to determine automatically at mount time.

**Comment by rojer** [comment]
> So you're getting ECC errors on the first writes to the blocks 0 and 1? Is this a heavily used storage chip?

not really a heavily used chip, i managed to screw up hw ecc by rewriting it the wrong way (trying to rewrite a region without erasing will screw up ECC). then, when i tried to create LFS over it, it failed.
i was able to fix it by manually erasing the sector in question.

> During format, littlefs doesn't trust any data on the blocks and should be erasing any blocks it uses before it writes data to them. Does this not match what you are seeing?

it does not. looks like it tried to page in contents of the root directory, it returned "corrupt" and that's where it ended.

**Comment by geky** [comment]
Oh! I just realized what's happening. You're right, littlefs is trying to read from blocks before writing to them. It doesn't actually care what the data is (as long as it doesn't change between reads), but isn't properly handling expected read failures.

This is just a shortcut to avoid writing both directory pairs unless needed, so we can just add some logic to write out 1s if the read fails. I'll put that together next chance I get.

**Comment by geky** [comment]
Sorry about the delay, this fix #76 should handle corrupt reads correctly. Does it look correct to you?

**Comment by rojer** [comment]
@geky i can't vouch for completeness or correctness since i'm not familiar with LFS internals but i verified that it does seem to be working as intended: i deliberately screwed ECC in all the blocks of the device, then tried to format with old and new code. old code bombed out, new code ran into 3 errors but was able to proceed and create the FS.

**Comment by geky** [comment]
Thanks for testing it! That helps a lot.
