### ISSUE TITLE
Can't find free space

### ISSUE THREAD

**Issue by e107steved** [ARMmbed/littlefs#88]
Had a strange problem occur twice now; once with the trunk code of 14th March, and once with the 27th July trunk (which is, I think, the most recent). Given that our software is under development, it's quite possible that the issue is outside littleFs. However some guidance on where to look would be useful.

Apparently at random, I have had an error of the following form:
`lfs warn:314: No more free space 2056`
(the final number varies)
It's a 'hard' error - not cleared by a reset/power cycle
The drive status (which uses the code posted in one of these issues) reports as follows:
Total size: 261120 bytes
Free space: 252160 bytes
Sector size: 128 bytes
Total sectors: 2040
The directory listing is available and reported individual file sizes are consistent with the above summary.
File contents of a random sample appear valid.
The vast majority of file writing is to my circular file with 100 52-byte records.
Read, write and erase sizes are all set to 128.
Lookahead is set to 128 blocks
It is possible that the problem was triggered by updating a different file. I'm running an RTOS, and have mutex-protected each LFS drive, so that shouldn't be a problem.

Any thoughts?

**Comment by e107steved** [comment]
Found the cause - an attempt to seek to a very large offset (not sure why, given the very simple calculation, but that's not your problem). Somehow several variables were (maybe are) getting corrupted.

**Comment by geky** [comment]
Ah, glad you were able to find the issue.

> an attempt to seek to a very large offset

This will fill the file with zeros. So it's possible you actual did run out of space.

**Comment by e107steved** [comment]
Thinking further about this, could a seek check against drive size or similar? That would certainly have found my problem quicker.
