### ISSUE TITLE
bug of lfs_cache_zero cause corruption

### ISSUE THREAD

**Issue by nstcl** [ARMmbed/littlefs#89]
The lfs_cache_zero will cause corruption if prog_size != read_size.
```
static inline void lfs_cache_zero(lfs_t *lfs, lfs_cache_t *pcache) {
    // zero to avoid information leak
    memset(pcache->buffer, 0xff, lfs->cfg->prog_size);
    pcache->block = CACHE_BLOCK_MAGIC;
}
```
The  lfs->cfg->prog_size is error here when prog_size != read_size, especially read_size<prog_size. When read_size<prog_size, the memset function will set part of memory that not belong to it to 0xff, this will cause secrious problem.
I have tested the bug on my board( stm32 + freertos 10.0.1 + littlefs 1.6)

**Comment by geky** [comment]
Good catch!

I had assumed lfs_cache_zero would only be used on prog caches, then used it for read caches. Here's a fix: https://github.com/ARMmbed/littlefs/pull/91

In the next major version (https://github.com/ARMmbed/littlefs/pull/85), the cache sizes will be the same and configured by a separate option.

Thanks for opening the issue
